services:
  db:
    image: mongo:6
    container_name: rxmanager-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rxuser
      MONGO_INITDB_ROOT_PASSWORD: rxpass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
